"use client";

import { motion } from "framer-motion";
import { Github, Linkedin, Mail, ExternalLink, Code2, Cpu, Globe, Rocket, Terminal as TerminalIcon, Sparkles } from "lucide-react";
import ChatInterface from "@/components/ChatInterface";
import ContactModal from "@/components/ContactModal";
import { useState } from "react";

const skills = [
  { group: "Core", items: ["Python", "JavaScript", "TypeScript", "SQL"] },
  { group: "Frontend & Mobile", items: ["React Native", "Expo", "React", "Android", "Next.js", "Tailwind CSS"] },
  { group: "Backend & Cloud", items: ["FastAPI", "PostgreSQL", "Render", "Docker", "Flask", "Alembic"] },
  { group: "ML/DL & AI", items: ["TensorFlow", "PyTorch", "Scikit Learn", "Keras", "LangChain", "Hugging Face", "Google Gemini", "OpenAI", "Ollama"] },
  { group: "Data Science", items: ["Pandas", "NumPy", "Matplotlib", "Seaborn", "Plotly"] },
  { group: "Tools", items: ["Git", "Jupyter", "VS Code", "Postman"] }
];

const projects = [
  {
    title: "AI Tutor",
    description: "Personalized learning paths generated by Gemini 1.5 Pro with real-time feedback.",
    tech: ["Python", "React", "Gemini", "FastAPI"],
    color: "from-blue-500 to-cyan-500",
  },
  {
    title: "Documind-AI",
    description: "Enterprise-grade document query system using RAG and vector embeddings.",
    tech: ["PostgreSQL", "FastAPI", "OpenAI", "LangChain"],
    color: "from-purple-500 to-pink-500",
  },
  {
    title: "NEEL",
    description: "Mobile Life Coach with real-time feedback loop and emotional intelligence.",
    tech: ["React Native", "Flask", "Docker", "TensorFlow"],
    color: "from-orange-500 to-red-500",
  }
];

export default function Home() {
  const [isContactOpen, setIsContactOpen] = useState(false);

  return (
    <main className="min-h-screen bg-[#030303] text-white selection:bg-cyan-500/30 overflow-x-hidden">
      <ContactModal isOpen={isContactOpen} onClose={() => setIsContactOpen(false)} />
      {/* Background Decorative Elements */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-blue-500/10 blur-[120px] rounded-full" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-purple-500/10 blur-[120px] rounded-full" />
      </div>

      <div className="relative max-w-7xl mx-auto px-6 py-12 lg:py-20 grid grid-cols-1 lg:grid-cols-12 gap-12">

        {/* Left Column: Content */}
        <div className="lg:col-span-7 space-y-16">

          {/* Hero Section */}
          <section className="space-y-8">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-cyan-500/30 bg-cyan-500/10 text-cyan-400 text-xs font-mono uppercase tracking-widest shadow-[0_0_15px_rgba(34,211,238,0.1)]"
            >
              <Sparkles size={12} className="animate-pulse" />
              Available for Innovation
            </motion.div>

            <div className="flex flex-col md:flex-row items-start md:items-center gap-8">
              <motion.div
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                className="relative group"
              >
                <div className="absolute -inset-1 bg-gradient-to-r from-cyan-500 to-blue-500 rounded-3xl blur opacity-30 group-hover:opacity-60 transition duration-500"></div>
                <div className="relative w-32 h-32 md:w-40 md:h-40 rounded-3xl overflow-hidden border border-white/10 glass">
                  <img
                    src="/karan_image.png"
                    alt="Karan"
                    className="w-full h-full object-cover grayscale group-hover:grayscale-0 transition-all duration-700 scale-105 group-hover:scale-110"
                  />
                </div>
              </motion.div>

              <div className="space-y-4">
                <motion.h1
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="text-7xl md:text-9xl font-black tracking-tighter bg-gradient-to-b from-white to-white/40 bg-clip-text text-transparent"
                >
                  Karan.
                </motion.h1>
                <motion.p
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.1 }}
                  className="text-xl md:text-2xl text-cyan-400 font-mono tracking-tight"
                >
                  // Fullstack Developer & Generative AI Developer
                </motion.p>
              </div>
            </div>

            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.2 }}
              className="flex flex-wrap gap-4"
            >
              <SocialLink icon={<Github size={20} />} href="https://github.com/Edge-Explorer" label="GitHub" />
              <SocialLink icon={<Linkedin size={20} />} href="https://linkedin.com/in/karan-shelar-779381343" label="LinkedIn" />
              <button
                onClick={() => setIsContactOpen(true)}
                className="flex items-center gap-3 px-4 py-2 glass rounded-2xl hover:text-cyan-400 hover:border-cyan-500/50 transition-all duration-300 group"
              >
                <span className="text-white/40 group-hover:text-cyan-400 transition-colors"><Mail size={20} /></span>
                <span className="text-sm font-mono text-white/60 group-hover:text-white transition-colors">Email</span>
              </button>
              <SocialLink icon={<ExternalLink size={20} />} href="https://drive.google.com/file/d/1QhYwPLs4nQjjvCFuEEjYx0Q8Gbcc7GMb/view?usp=drive_link" label="Resume" />
            </motion.div>
          </section>

          {/* Tech Stack Horizontal Scroll/Grid */}
          <section className="space-y-6">
            <h2 className="text-sm font-mono text-white/40 uppercase tracking-[0.3em] flex items-center gap-2">
              <TerminalIcon size={14} className="text-cyan-500" />
              Technical_Stack.log
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {skills.map((skillGroup, i) => (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.05 }}
                  key={skillGroup.group}
                  className="glass p-5 rounded-2xl border-white/5 hover:border-cyan-500/20 transition-colors group"
                >
                  <h3 className="text-xs font-mono text-cyan-400/70 mb-3 uppercase tracking-wider">{skillGroup.group}</h3>
                  <div className="flex flex-wrap gap-2">
                    {skillGroup.items.map(skill => (
                      <span key={skill} className="px-2 py-1 rounded-md bg-white/5 border border-white/5 text-[11px] text-white/70 group-hover:text-white transition-colors">
                        {skill}
                      </span>
                    ))}
                  </div>
                </motion.div>
              ))}
            </div>
          </section>

          {/* Featured Projects */}
          <section className="space-y-8">
            <div className="flex justify-between items-end">
              <h2 className="text-sm font-mono text-white/40 uppercase tracking-[0.3em]">Featured_Works</h2>
              <span className="text-[10px] font-mono text-cyan-500/50 underline cursor-pointer hover:text-cyan-400 transition-colors">View All Repos</span>
            </div>

            <div className="grid grid-cols-1 gap-6">
              {projects.map((project, idx) => (
                <motion.div
                  key={project.title}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  className="group relative p-8 glass rounded-3xl border-white/5 hover:border-white/10 transition-all duration-500 overflow-hidden"
                >
                  <div className={`absolute top-0 right-0 w-32 h-32 bg-gradient-to-br ${project.color} opacity-[0.03] group-hover:opacity-[0.1] blur-2xl transition-opacity animate-pulse`} />

                  <div className="relative z-10 grid md:grid-cols-2 gap-8 items-center">
                    <div className="space-y-4">
                      <div className="flex items-center gap-3">
                        <div className={`p-2 rounded-xl bg-gradient-to-br ${project.color} text-white shadow-lg shadow-black/20`}>
                          {idx === 0 ? <Cpu size={20} /> : idx === 1 ? <Globe size={20} /> : <Rocket size={20} />}
                        </div>
                        <h3 className="text-2xl font-bold tracking-tight">{project.title}</h3>
                      </div>
                      <p className="text-white/60 leading-relaxed font-light">
                        {project.description}
                      </p>
                      <div className="flex flex-wrap gap-2">
                        {project.tech.map(t => (
                          <span key={t} className="text-[10px] font-mono px-2 py-1 rounded bg-white/5 text-white/40">
                            {t}
                          </span>
                        ))}
                      </div>
                    </div>
                    <div className="flex justify-end gap-4">
                      <div className="w-full aspect-video rounded-xl bg-white/5 border border-white/10 overflow-hidden group-hover:border-cyan-500/30 transition-colors relative">
                        {/* Placeholder for project screenshot */}
                        <div className="absolute inset-0 flex items-center justify-center text-[10px] font-mono text-white/20 uppercase tracking-[0.3em]">
                          Preview_Unavailable
                        </div>
                        <div className="absolute bottom-4 right-4 p-2 glass rounded-full text-white/40 group-hover:text-cyan-400 transition-colors">
                          <ExternalLink size={16} />
                        </div>
                      </div>
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          </section>

        </div>

        {/* Right Column: AI Terminal */}
        <div className="lg:col-span-5 relative">
          <div className="lg:sticky lg:top-12 space-y-8">
            <div className="flex items-center justify-between">
              <div className="space-y-1">
                <h2 className="text-sm font-mono text-white/40 uppercase tracking-[0.3em]">AI_Subsystem.exe</h2>
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-cyan-500 animate-pulse shadow-[0_0_8px_rgba(34,211,238,0.8)]" />
                  <span className="text-[10px] text-cyan-400/80 font-mono">Kernel 2.0.Flash // Online</span>
                </div>
              </div>
              <div className="px-3 py-1 rounded border border-white/5 bg-white/5 text-[10px] font-mono text-white/40 uppercase">
                Latency: 24ms
              </div>
            </div>

            <ChatInterface />

            {/* Proficiency Dashboard */}
            <div className="glass p-8 rounded-3xl border-white/5 relative overflow-hidden group">
              <div className="absolute inset-0 bg-gradient-to-br from-cyan-500/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
              <h4 className="text-sm font-mono text-white/60 mb-6 flex items-center gap-2 uppercase tracking-widest">
                System_Core_Metrics
              </h4>
              <div className="space-y-6">
                <SkillBar label="Backend Architecture" progress={95} color="bg-cyan-500" />
                <SkillBar label="AI Implementation" progress={88} color="bg-blue-500" />
                <SkillBar label="Frontend Engineering" progress={82} color="bg-purple-500" />
                <SkillBar label="Mathematical Modeling" progress={75} color="bg-indigo-500" />
              </div>
            </div>

            {/* Footer / Contact Overlay */}
            <div className="text-center space-y-2 py-4">
              <p className="text-[10px] font-mono text-white/20 uppercase tracking-[0.4em]">Designed & Developed by Karan</p>
              <p className="text-[10px] font-mono text-cyan-500/30">© 2026 // Built with Next.js & FastAPI</p>
            </div>
          </div>
        </div>

      </div>
    </main>
  );
}

function SocialLink({ icon, href, label }: { icon: React.ReactNode; href: string; label: string }) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="flex items-center gap-3 px-4 py-2 glass rounded-2xl hover:text-cyan-400 hover:border-cyan-500/50 transition-all duration-300 group"
    >
      <span className="text-white/40 group-hover:text-cyan-400 transition-colors">{icon}</span>
      <span className="text-sm font-mono text-white/60 group-hover:text-white transition-colors">{label}</span>
    </a>
  );
}

function SkillBar({ label, progress, color }: { label: string; progress: number; color: string }) {
  return (
    <div className="space-y-2">
      <div className="flex justify-between text-[10px] font-mono text-white/40 uppercase tracking-widest">
        <span>{label}</span>
        <span>{progress}%</span>
      </div>
      <div className="h-1.5 bg-white/5 rounded-full overflow-hidden">
        <motion.div
          initial={{ width: 0 }}
          whileInView={{ width: `${progress}%` }}
          transition={{ duration: 1.5, ease: "easeOut" }}
          className={`h-full ${color} shadow-[0_0_15px_rgba(34,211,238,0.3)]`}
        />
      </div>
    </div>
  );
}
