"use client";

import { motion, AnimatePresence } from "framer-motion";
import {
  Github, Linkedin, Mail, ExternalLink, Code2, Cpu, Globe, Rocket, Sparkles,
  Terminal, Database, Layout, Smartphone, Cloud, Layers, Cpu as AiIcon,
  Binary, GitBranch, Box, FileCode, Search, Server, Monitor
} from "lucide-react";
import ChatInterface from "@/components/ChatInterface";
import ContactModal from "@/components/ContactModal";
import { useState } from "react";

const skills = [
  {
    group: "Core",
    items: [
      { name: "Python", info: "High-level programming for AI & Data Science.", icon: "python" },
      { name: "JavaScript", info: "Dynamic web logic and interactive UI.", icon: "javascript" },
      { name: "TypeScript", info: "Scaling JS with robust static typing.", icon: "typescript" },
      { name: "SQL", info: "Relational data management and complex queries.", icon: "mysql" }
    ]
  },
  {
    group: "Frontend & Mobile",
    items: [
      { name: "React", info: "Building component-based immersive interfaces.", icon: "react" },
      { name: "Next.js", info: "Modern fullstack framework with SSR/SSG.", icon: "nextjs" },
      { name: "Tailwind CSS", info: "Rapid styling with utility-first CSS.", icon: "tailwindcss" },
      { name: "React Native", info: "Cross-platform native mobile applications.", icon: "react" },
      { name: "Expo", info: "Accelerated development for React Native.", local: "/skills/expo.png" },
      { name: "Android", info: "Native mobile development for Android devices.", icon: "android" }
    ]
  },
  {
    group: "Backend & Cloud",
    items: [
      { name: "FastAPI", info: "High-performance Python API development.", icon: "fastapi" },
      { name: "PostgreSQL", info: "Robust, open-source relational database.", icon: "postgresql" },
      { name: "Docker", info: "Containerization for consistent deployments.", icon: "docker" },
      { name: "Flask", info: "Micro web framework for agile Python apps.", icon: "flask" },
      { name: "Render", info: "Fast, simple cloud platform for web apps.", local: "/skills/render.jpg" },
      { name: "Alembic", info: "Database migration tool for SQLAlchemy.", lucide: Database }
    ]
  },
  {
    group: "Generative AI",
    items: [
      { name: "LangChain", info: "Framework for building LLM-powered apps.", local: "/skills/langchain.png" },
      { name: "Google Gemini", info: "Multimodal AI models for generative tasks.", local: "/skills/gemini.png" },
      { name: "OpenAI", info: "Cutting-edge models like GPT-4 and DALL-E.", local: "/skills/openai.png" },
      { name: "Hugging Face", info: "Hub for modern transformers and public models.", local: "/skills/huggingface.png" },
      { name: "Ollama", info: "Running large language models locally.", local: "/skills/ollama.png" },
      { name: "Keras", info: "Deep learning API for fast experimentation.", local: "/skills/keras.png" }
    ]
  },
  {
    group: "ML & Data Science",
    items: [
      { name: "TensorFlow", info: "Open-source platform for end-to-end ML.", icon: "tensorflow" },
      { name: "PyTorch", info: "Flexible deep learning for research and prod.", icon: "pytorch" },
      { name: "Scikit Learn", info: "Simple and efficient tools for predictive data.", local: "/skills/scikitlearn.jpg" },
      { name: "Pandas", info: "Powerful data manipulation and analysis.", icon: "pandas" },
      { name: "NumPy", info: "Fundamental package for scientific computing.", icon: "numpy" },
      { name: "Matplotlib", info: "Comprehensive library for static/animated plots.", local: "/skills/matplotlib.png" }
    ]
  },
  {
    group: "Tools",
    items: [
      { name: "Git", info: "Version control for tracking code changes.", icon: "git" },
      { name: "Postman", info: "Platform for building and using APIs.", local: "/skills/postman.jpg" },
      { name: "VS Code", info: "Extensible code editor for modern development.", icon: "vscode" },
      { name: "Jupyter", info: "Interactive computing across all languages.", icon: "jupyter" }
    ]
  }
];

const projects = [
  {
    title: "AI Tutor",
    description: "Personalized learning paths generated by Gemini 1.5 Pro with real-time feedback.",
    tech: ["Python", "React", "Gemini", "FastAPI"],
    color: "from-blue-500 to-cyan-500",
  },
  {
    title: "Documind-AI",
    description: "Enterprise-grade document query system using RAG and vector embeddings.",
    tech: ["PostgreSQL", "FastAPI", "OpenAI", "LangChain"],
    color: "from-purple-500 to-pink-500",
  },
  {
    title: "NEEL",
    description: "Mobile Life Coach with real-time feedback loop and emotional intelligence.",
    tech: ["React Native", "Flask", "Docker", "TensorFlow"],
    color: "from-orange-500 to-red-500",
  }
];

function SkillLogo({ skill }: { skill: any }) {
  if (skill.local) {
    return (
      <img
        src={skill.local}
        className="w-8 h-8 object-contain group-hover:scale-110 transition-transform"
        alt={skill.name}
      />
    );
  }

  if (skill.lucide) {
    const LucideIcon = skill.lucide;
    return <LucideIcon className="w-7 h-7 text-indigo-400 group-hover:text-white transition-colors" />;
  }

  return (
    <img
      src={`https://cdn.jsdelivr.net/gh/devicons/devicon/icons/${skill.icon}/${skill.icon}-original.svg`}
      onError={(e) => {
        (e.target as any).style.display = 'none';
        (e.target as any).parentElement.innerHTML = `<span class="text-xs font-bold text-white/20">${skill.name[0]}</span>`;
      }}
      className="w-7 h-7 object-contain group-hover:scale-110 transition-transform"
      alt={skill.name}
    />
  );
}

export default function Home() {
  const [isContactOpen, setIsContactOpen] = useState(false);
  const [isAIChatOpen, setIsAIChatOpen] = useState(false);
  const [activeSkill, setActiveSkill] = useState<any | null>(null);

  return (
    <main className="min-h-screen bg-background text-white selection:bg-indigo-500/30 overflow-x-hidden bg-gradient-mesh pb-20">
      <ContactModal isOpen={isContactOpen} onClose={() => setIsContactOpen(false)} />
      <ChatInterface isOpen={isAIChatOpen} onClose={() => setIsAIChatOpen(false)} />

      <div className="relative max-w-7xl mx-auto px-6 py-12 lg:py-32 flex flex-col items-center">

        <motion.button
          onClick={() => setIsAIChatOpen(true)}
          initial={{ scale: 0, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          whileHover={{ scale: 1.1, rotate: 5 }}
          className="fixed bottom-10 right-10 z-[150] group"
        >
          <div className="absolute -inset-2 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 rounded-full blur-xl opacity-40 group-hover:opacity-100 transition duration-500 animate-pulse" />
          <div className="relative w-24 h-24 rounded-full overflow-hidden border-4 border-white/20 glass shadow-2xl">
            <img src="/karan_image.png" alt="AI Agent" className="w-full h-full object-cover" />
            <div className="absolute inset-0 bg-indigo-500/20 group-hover:bg-transparent transition-colors" />
            <div className="absolute bottom-1 right-1 w-6 h-6 bg-green-500 border-2 border-white rounded-full" />
          </div>
        </motion.button>

        <section className="w-full text-center space-y-16 mb-32">
          <div className="flex flex-col items-center gap-10">
            <div className="flex flex-col lg:flex-row items-center justify-center gap-8 lg:gap-14">
              <motion.h1
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="text-6xl md:text-8xl lg:text-[9rem] font-black tracking-tight leading-none bg-gradient-to-b from-white to-white/30 bg-clip-text text-transparent"
              >
                Karan Rohidas Shelar
              </motion.h1>

              <motion.div
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                className="relative group shrink-0"
              >
                <div className="absolute -inset-2 bg-gradient-to-r from-indigo-500 to-purple-500 rounded-full blur opacity-50 group-hover:opacity-100 transition duration-500"></div>
                <div className="relative w-32 h-32 md:w-56 md:h-56 rounded-full overflow-hidden border-4 border-white/20 shadow-2xl">
                  <img src="/karan_image.png" alt="Karan" className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105" />
                </div>
              </motion.div>
            </div>

            <motion.p
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.2 }}
              className="text-xl md:text-3xl text-indigo-400 font-medium tracking-wide uppercase"
            >
              Generative AI Developer
            </motion.p>
          </div>

          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.3 }}
            className="flex flex-wrap justify-center gap-6"
          >
            <SocialLink icon={<Github size={24} />} href="https://github.com/Edge-Explorer" label="GitHub" />
            <SocialLink icon={<Linkedin size={24} />} href="https://linkedin.com/in/karan-shelar-779381343" label="LinkedIn" />
            <button
              onClick={() => setIsContactOpen(true)}
              className="px-8 py-4 bg-white text-black font-bold rounded-2xl hover:bg-indigo-500 hover:text-white transition-all shadow-xl flex items-center gap-3"
            >
              <Mail size={20} /> Connect Now
            </button>
            <SocialLink icon={<ExternalLink size={24} />} href="https://drive.google.com/file/d/1QhYwPLs4nQjjvCFuEEjYx0Q8Gbcc7GMb/view?usp=drive_link" label="Resume" />
          </motion.div>
        </section>

        <section className="w-full max-w-6xl space-y-20 py-24 border-y border-white/5">
          <div className="text-center space-y-4">
            <h2 className="text-sm font-bold text-indigo-400 uppercase tracking-[0.5em]">Core Expertise</h2>
            <p className="text-4xl md:text-6xl font-black text-white px-4">Mastering the Tech Stack</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
            {skills.map((group, i) => (
              <motion.div
                key={group.group}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="p-10 rounded-[3rem] glass border-white/5 group hover:border-indigo-500/30 transition-all duration-500"
              >
                <h3 className="text-sm font-black text-white/40 mb-10 uppercase tracking-widest group-hover:text-indigo-400 transition-colors">
                  {group.group}
                </h3>
                <div className="grid grid-cols-4 gap-6">
                  {group.items.map(skill => (
                    <div
                      key={skill.name}
                      onMouseEnter={() => setActiveSkill(skill)}
                      onMouseLeave={() => setActiveSkill(null)}
                      className="flex flex-col items-center gap-3 cursor-help relative group"
                    >
                      <div className="w-14 h-14 rounded-2xl bg-white/5 border border-white/5 flex items-center justify-center hover:bg-indigo-500/10 hover:border-indigo-500/40 transition-all duration-300">
                        <SkillLogo skill={skill} />
                      </div>
                      <span className="text-[10px] font-bold text-white/30 uppercase tracking-tighter text-center">{skill.name}</span>

                      <AnimatePresence>
                        {activeSkill?.name === skill.name && (
                          <motion.div
                            initial={{ opacity: 0, y: 10, scale: 0.9 }}
                            animate={{ opacity: 1, y: 0, scale: 1 }}
                            exit={{ opacity: 0, y: 10, scale: 0.9 }}
                            className="absolute bottom-full mb-4 z-20 w-48 p-4 glass rounded-2xl border border-white/10 shadow-2xl pointer-events-none"
                          >
                            <p className="text-[11px] text-indigo-400 font-bold mb-1">{skill.name}</p>
                            <p className="text-[10px] text-white/60 leading-tight">{skill.info}</p>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
                  ))}
                </div>
              </motion.div>
            ))}
          </div>
        </section>

        <section className="w-full max-w-6xl space-y-24 py-32">
          <div className="flex flex-col items-center text-center space-y-6">
            <h2 className="text-6xl md:text-8xl font-black tracking-tighter leading-none">Selected <br /> <span className="text-indigo-500">Creations</span></h2>
          </div>

          <div className="space-y-32">
            {projects.map((project, idx) => (
              <motion.div
                key={project.title}
                initial={{ opacity: 0 }}
                whileInView={{ opacity: 1 }}
                viewport={{ once: true, margin: "-100px" }}
                className={`flex flex-col ${idx % 2 === 0 ? 'lg:flex-row' : 'lg:flex-row-reverse'} gap-16 items-center`}
              >
                <div className="flex-1 space-y-8 text-left">
                  <div className="space-y-4">
                    <div className={`inline-block p-4 rounded-3xl bg-gradient-to-br ${project.color} text-white shadow-2xl`}>
                      {idx === 0 ? <Cpu size={40} /> : idx === 1 ? <Globe size={40} /> : <Rocket size={40} />}
                    </div>
                    <h3 className="text-5xl md:text-7xl font-black tracking-tighter">{project.title}</h3>
                  </div>
                  <p className="text-2xl text-white/60 font-light leading-snug">
                    {project.description}
                  </p>
                  <div className="flex flex-wrap gap-3">
                    {project.tech.map(t => (
                      <span key={t} className="text-xs font-bold px-4 py-2 rounded-xl bg-white/5 border border-white/5 text-indigo-400 uppercase">
                        {t}
                      </span>
                    ))}
                  </div>
                </div>
                <div className="flex-1 w-full aspect-[4/3] rounded-[4rem] overflow-hidden relative group">
                  <div className={`absolute inset-0 bg-gradient-to-br ${project.color} opacity-20`} />
                  <div className="absolute inset-0 glass-vibrant" />
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="text-[12px] font-bold text-white font-black uppercase tracking-[0.5em] opacity-30">Render_Matrix</div>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </section>

        <footer className="w-full py-20 border-t border-white/5 mt-32 text-center space-y-4">
          <p className="text-6xl font-black tracking-tighter opacity-10 uppercase">KRS 2026</p>
          <p className="text-[10px] font-bold text-white/20 uppercase tracking-[1em]">Karan Rohidas Shelar</p>
        </footer>

      </div>
    </main>
  );
}

function SocialLink({ icon, href, label }: { icon: React.ReactNode; href: string; label: string }) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="flex items-center gap-3 px-6 py-3 glass rounded-2xl hover:text-indigo-400 hover:border-indigo-500/50 transition-all duration-300 group"
    >
      <span className="text-white/40 group-hover:text-indigo-400 transition-colors">{icon}</span>
      <span className="text-sm font-bold text-white/60 group-hover:text-white transition-colors uppercase tracking-widest">{label}</span>
    </a>
  );
}
