"use client";

import { motion } from "framer-motion";
import { Github, Linkedin, Mail, ExternalLink, Code2, Cpu, Globe, Rocket, Sparkles } from "lucide-react";
import ChatInterface from "@/components/ChatInterface";
import ContactModal from "@/components/ContactModal";
import { useState } from "react";

const skills = [
  { group: "Core", items: ["Python", "JavaScript", "TypeScript", "SQL"] },
  { group: "Frontend & Mobile", items: ["React Native", "Expo", "React", "Android", "Next.js", "Tailwind CSS"] },
  { group: "Backend & Cloud", items: ["FastAPI", "PostgreSQL", "Render", "Docker", "Flask", "Alembic"] },
  { group: "ML/DL & AI", items: ["TensorFlow", "PyTorch", "Scikit Learn", "Keras", "LangChain", "Hugging Face", "Google Gemini", "OpenAI", "Ollama"] },
  { group: "Data Science", items: ["Pandas", "NumPy", "Matplotlib", "Seaborn", "Plotly"] },
  { group: "Tools", items: ["Git", "Jupyter", "VS Code", "Postman"] }
];

const projects = [
  {
    title: "AI Tutor",
    description: "Personalized learning paths generated by Gemini 1.5 Pro with real-time feedback.",
    tech: ["Python", "React", "Gemini", "FastAPI"],
    color: "from-blue-500 to-cyan-500",
  },
  {
    title: "Documind-AI",
    description: "Enterprise-grade document query system using RAG and vector embeddings.",
    tech: ["PostgreSQL", "FastAPI", "OpenAI", "LangChain"],
    color: "from-purple-500 to-pink-500",
  },
  {
    title: "NEEL",
    description: "Mobile Life Coach with real-time feedback loop and emotional intelligence.",
    tech: ["React Native", "Flask", "Docker", "TensorFlow"],
    color: "from-orange-500 to-red-500",
  }
];

export default function Home() {
  const [isContactOpen, setIsContactOpen] = useState(false);
  const [isAIChatOpen, setIsAIChatOpen] = useState(false);

  return (
    <main className="min-h-screen bg-background text-white selection:bg-indigo-500/30 overflow-x-hidden bg-gradient-mesh">
      <ContactModal isOpen={isContactOpen} onClose={() => setIsContactOpen(false)} />
      <ChatInterface isOpen={isAIChatOpen} onClose={() => setIsAIChatOpen(false)} />

      {/* Background Decorative Elements */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-blue-500/10 blur-[120px] rounded-full" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-purple-500/10 blur-[120px] rounded-full" />
      </div>

      <div className="relative max-w-7xl mx-auto px-6 py-12 lg:py-32 flex flex-col items-center text-center">

        {/* Floating AI Trigger */}
        <motion.button
          onClick={() => setIsAIChatOpen(true)}
          initial={{ scale: 0, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          whileHover={{ scale: 1.1, rotate: 5 }}
          className="fixed bottom-10 right-10 z-[150] group"
        >
          <div className="absolute -inset-2 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 rounded-full blur-xl opacity-40 group-hover:opacity-100 transition duration-500 animate-pulse" />
          <div className="relative w-24 h-24 rounded-full overflow-hidden border-4 border-white/20 glass shadow-2xl">
            <img src="/karan_image.png" alt="AI Agent" className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110" />
            <div className="absolute inset-0 bg-indigo-500/20 group-hover:bg-transparent transition-colors" />
            <div className="absolute bottom-1 right-1 w-6 h-6 bg-green-500 border-2 border-white rounded-full" />
          </div>
          <div className="absolute -top-12 right-0 bg-indigo-500 text-white text-[10px] font-black px-3 py-1.5 rounded-xl opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap uppercase tracking-widest shadow-xl">
            Initialize Neural Chat
          </div>
        </motion.button>

        {/* Hero Section */}
        <section className="space-y-12 mb-24">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="inline-flex items-center gap-3 px-6 py-2 rounded-full border border-indigo-500/30 bg-indigo-500/10 text-indigo-400 text-xs font-black uppercase tracking-[0.2em] shadow-lg"
          >
            <Sparkles size={14} className="animate-pulse" />
            Generative AI Pioneer
          </motion.div>

          <div className="space-y-6">
            <motion.h1
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              className="text-7xl md:text-[10rem] font-black tracking-tighter leading-[0.8] bg-gradient-to-b from-white via-white to-white/20 bg-clip-text text-transparent"
            >
              Karan <br /> Rohidas <br /> Shelar.
            </motion.h1>
            <motion.p
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className="text-xl md:text-2xl text-indigo-400 font-mono tracking-tight"
            >
              // Generative AI Developer
            </motion.p>
          </div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="flex flex-wrap justify-center gap-6"
          >
            <SocialLink icon={<Github size={24} />} href="https://github.com/Edge-Explorer" label="GitHub" />
            <SocialLink icon={<Linkedin size={24} />} href="https://linkedin.com/in/karan-shelar-779381343" label="LinkedIn" />
            <button
              onClick={() => setIsContactOpen(true)}
              className="flex items-center gap-4 px-8 py-4 bg-white text-black font-black rounded-3xl hover:bg-indigo-500 hover:text-white transition-all duration-300 shadow-[0_20px_50px_rgba(255,255,255,0.1)] hover:shadow-indigo-500/40 group"
            >
              <Mail size={24} />
              <span className="font-mono text-sm uppercase tracking-widest">Connect_System</span>
            </button>
            <SocialLink icon={<ExternalLink size={24} />} href="https://drive.google.com/file/d/1QhYwPLs4nQjjvCFuEEjYx0Q8Gbcc7GMb/view?usp=drive_link" label="Resume" />
          </motion.div>
        </section>

        {/* Dynamic Skills Cloud */}
        <section className="w-full max-w-5xl space-y-16 py-20">
          <div className="text-center space-y-4">
            <h2 className="text-sm font-mono text-indigo-400 uppercase tracking-[0.5em]">Neural_Cognition_Matrix</h2>
            <div className="w-20 h-1 bg-gradient-to-r from-indigo-500 to-purple-500 mx-auto rounded-full" />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {skills.map((skillGroup, i) => (
              <motion.div
                initial={{ opacity: 0, scale: 0.9 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                key={skillGroup.group}
                className="p-10 rounded-[3rem] glass border-white/5 hover:border-indigo-500/40 transition-all duration-700 group hover:-translate-y-2 overflow-hidden relative"
              >
                <div className="absolute top-0 right-0 w-24 h-24 bg-indigo-500/10 blur-3xl rounded-full opacity-0 group-hover:opacity-100 transition-opacity" />
                <h3 className="text-sm font-black text-white/40 mb-8 uppercase tracking-[0.2em] group-hover:text-indigo-400 transition-colors">{skillGroup.group}</h3>
                <div className="flex flex-wrap gap-3">
                  {skillGroup.items.map(skill => (
                    <span key={skill} className="px-4 py-2 rounded-2xl bg-white/5 border border-white/5 text-xs font-mono text-white/50 group-hover:text-white transition-colors hover:bg-indigo-500/20 hover:border-indigo-500/30">
                      {skill}
                    </span>
                  ))}
                </div>
              </motion.div>
            ))}
          </div>
        </section>

        {/* Innovative Project Layout */}
        <section className="w-full max-w-6xl space-y-24 py-32">
          <div className="flex flex-col items-center text-center space-y-6">
            <h2 className="text-6xl md:text-8xl font-black tracking-tighter">Genesis <span className="text-indigo-500 underline decoration-purple-500/30">Archives.</span></h2>
            <p className="text-white/40 font-mono tracking-widest uppercase text-xs">Architecting the future of Generative Intelligence</p>
          </div>

          <div className="space-y-32">
            {projects.map((project, idx) => (
              <motion.div
                key={project.title}
                initial={{ opacity: 0 }}
                whileInView={{ opacity: 1 }}
                viewport={{ once: true, margin: "-100px" }}
                className={`flex flex-col ${idx % 2 === 0 ? 'lg:flex-row' : 'lg:flex-row-reverse'} gap-16 items-center`}
              >
                <div className="flex-1 space-y-8 text-left">
                  <div className="space-y-4">
                    <div className={`inline-block p-4 rounded-3xl bg-gradient-to-br ${project.color} text-white shadow-2xl animate-float`}>
                      {idx === 0 ? <Cpu size={40} /> : idx === 1 ? <Globe size={40} /> : <Rocket size={40} />}
                    </div>
                    <h3 className="text-5xl md:text-7xl font-black tracking-tighter">{project.title}</h3>
                  </div>
                  <p className="text-2xl text-white/60 font-light leading-snug">
                    {project.description}
                  </p>
                  <div className="flex flex-wrap gap-3">
                    {project.tech.map(t => (
                      <span key={t} className="text-xs font-mono px-4 py-2 rounded-xl bg-white/5 border border-white/5 text-indigo-400/80 uppercase">
                        {t}
                      </span>
                    ))}
                  </div>
                  <motion.button
                    whileHover={{ x: 10 }}
                    className="flex items-center gap-4 text-sm font-black uppercase tracking-[0.3em] text-white/40 hover:text-indigo-400 transition-colors"
                  >
                    Explore System <ExternalLink size={16} />
                  </motion.button>
                </div>
                <div className="flex-1 w-full aspect-[4/3] rounded-[4rem] overflow-hidden relative group">
                  <div className={`absolute inset-0 bg-gradient-to-br ${project.color} opacity-20 group-hover:opacity-40 transition-opacity duration-700`} />
                  <div className="absolute inset-0 glass-vibrant group-hover:blur-sm transition-all duration-700" />
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="text-[12px] font-mono text-white font-black uppercase tracking-[0.5em] opacity-30 group-hover:opacity-100 transition-opacity">Neural_Render_Pending</div>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </section>

        {/* Footer */}
        <footer className="w-full py-20 border-t border-white/5 mt-32 space-y-8">
          <div className="flex justify-center gap-12">
            <a href="#" className="text-xs font-mono text-white/20 hover:text-indigo-400 transition-colors tracking-widest uppercase">System_Status: Optimal</a>
            <a href="#" className="text-xs font-mono text-white/20 hover:text-indigo-400 transition-colors tracking-widest uppercase">Encryption: AES-256</a>
          </div>
          <div className="text-center space-y-4">
            <p className="text-6xl font-black tracking-tighter opacity-10">KRS_OS_2026</p>
            <p className="text-[10px] font-mono text-white/10 uppercase tracking-[1em]">Generative AI Developer // Karan Rohidas Shelar</p>
          </div>
        </footer>

      </div>
    </main>
  );
}

function SocialLink({ icon, href, label }: { icon: React.ReactNode; href: string; label: string }) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="flex items-center gap-3 px-4 py-2 glass rounded-2xl hover:text-indigo-400 hover:border-indigo-500/50 transition-all duration-300 group"
    >
      <span className="text-white/40 group-hover:text-indigo-400 transition-colors">{icon}</span>
      <span className="text-sm font-mono text-white/60 group-hover:text-white transition-colors">{label}</span>
    </a>
  );
}

function SkillBar({ label, progress, color }: { label: string; progress: number; color: string }) {
  return (
    <div className="space-y-2">
      <div className="flex justify-between text-[10px] font-mono text-white/40 uppercase tracking-widest">
        <span>{label}</span>
        <span>{progress}%</span>
      </div>
      <div className="h-1.5 bg-white/5 rounded-full overflow-hidden">
        <motion.div
          initial={{ width: 0 }}
          whileInView={{ width: `${progress}%` }}
          transition={{ duration: 1.5, ease: "easeOut" }}
          className={`h-full ${color} shadow-[0_0_15px_rgba(34,211,238,0.3)]`}
        />
      </div>
    </div>
  );
}
